SSAFYnity/Job-Preparation-Challenge-6th

Baekjoon/골드바흐의 추측/골드바흐의추측_전규훈.cpp
#4 
소수 판별의 경우에는 에라토스테네스의 체 라는 유명한 판별 알고리즘을 사용하여 분류하였습니다.
두 수의 차이가 적은 수를 출력해아하기 때문에, 그리디하게 탐색을 진행했습니다.
오랜만에 푸는 정수론 문제여서 재밌게 풀었던 것 같습니다 :)
- 에라토스테네스의 체 알고리즘을 사용하여 시간복잡도를 줄임(O(n**0.5)
- 사전에 소수 판별 배열을 생성해주어, 불필요한 추가 계산 방
1. 컨벤션이 올바르지 않다면, Request Changes 해주세요.
2. 제출자의 풀이코드의 좋은 점 혹은 개선사항을 남기고 Approve 해주세요.
=> solved 골드바흐의추측 - 136ms 2060KB

Baekjoon/골드바흐의 추측/골드바흐의추측_전규훈.cpp, Programmers/여행경로/여행경로_전규훈.c++
#5 
문자열 노드 처리에서 고민이 필요했던 문제였습니다.
- BFS 탐색 시, 중복 노드 탐색이 불가함 => DFS로 탐색 진행
- visited 배열의 idx와 티켓 idx 일치시키기
1. 컨벤션이 올바르지 않다면, Request Changes 해주세요.
2. 제출자의 풀이코드의 좋은 점 혹은 개선사항을 남기고 Approve 해주세요.
=> solved 여행경로 - 0.03ms 4.17MB

Baekjoon/골드바흐의 추측/골드바흐의추측_전규훈.cpp, Baekjoon/인간-컴퓨터 상호작용/인간-컴퓨터상호작용_전규훈.c++, Programmers/여행경로/여행경로_전규훈.c++
#6 
누적합 아이디어 생각이 바로 떠오르지는 않았습니다. .
누적합 관련 문제를 더 많이 풀어봐야 할 것 같습니다.
- 누적합
- 누적합을 위한 2차원 배열 설정
1. 컨벤션이 올바르지 않다면, Request Changes 해주세요.
2. 제출자의 풀이코드의 좋은 점 혹은 개선사항을 남기고 Approve 해주세요.
=> solved 인간-컴퓨터 상호작용 - 84ms 22.8MB

Programmers/입국심사/입국심사_전규훈.cpp
#7 
최근에 풀었던 문제라 쉽게 풀었씁니다.
- 이분탐색
- right의 범위를 최대한 길게 설정. (입력 범위를 잘 확인하기)
1. 컨벤션이 올바르지 않다면, Request Changes 해주세요.
2. 제출자의 풀이코드의 좋은 점 혹은 개선사항을 남기고 Approve 해주세요.
=> solved 입국심사 - 42.98ms 6.58MB

Baekjoon/골드바흐의 추측/골든바흐의추측_김수빈.java
=> solved 골든바흐의 추측 - 2552ms 53628kb

Baekjoon/골드바흐의추측/골드바흐의추측_허승경.java
=> solved 골드바흐의추측 - 164ms 17.184mb

Programmers/여행경로/여행경로_허승경.java
#5 
티켓 경로를 기준으로 방문 처리 해줘야 한다는 부분에서 살짝 헷갈렸습니다. 
- dfs
=> solved 여행경로 - 12.74ms 89.2mb

Baekjoon/인간-컴퓨터상호작용/인간-컴퓨터상호작용_허승경.java
#6 
누적합 아이디어가 바로 떠오르지 않아서 시간이 걸렸습니다.
- 누적합
=> solved 인간-컴퓨터상호작용 - 776ms 110.216mb

Baekjoon/인간-컴퓨터 상호작용/인간-컴퓨터상호작용_김수빈.java
=> solved 인간-컴퓨터 상호작용 - 652ms 94464kb

Programmers/여행경로/여행경로_김수빈.java
=> solved 여행경로 - 1.50ms, 85.1mb

Programmers/입국심사/입국심사_허승경.java
#7 
구현으로 풀다가 시간초과가 발생해서 이분탐색으로 다시 풀었습니다.
시간을 이분탐색하다는 아이디어를 바로 떠올리기 어려웠습니다.
- 이분탐색
- 정렬
=> sovled 입국심사 - 138.56ms 109mb

Programmers/입국심사/입국심사_김수빈.java
=> solved 입국심사 - 114.16ms, 104MB

Baekjoon/공주님의정원/공주님의정원_김수빈.java
#8 공주님의 원
공주님한테 돈을 아끼다니 쪼잔 왕
- 인덱스
=> solved 공주님의 정원 - 400ms, 54972kb

Baekjoon/공주님의정원/공주님의정원_허승경.java
#8 
머릿속으로는 이렇게 풀면 되겠다! 했지만, 막상 구현하려고 하니 어떤 자료구조로 저장하고,
어떻게 탐색하지 고민 된 문제였습니다.
처음에는 시작 월/일 마감 월/일을 각각 나누어 2차원 배열에 저장하였지만 아이디어를 얻어 세자리수로 변환하여 다시 풀었습니다.
푸는 과정은 시간이 걸렸지만, 오히려 취약점을 알게 해주어 좋은 것 같습니다.
- 정렬
- 날짜 형식
=> solved 공주님의정원 - 472ms 53.440mb

Programmers/튜플/튜플_박단비.py
=> solved 튜플 - 496.61ms 19.5mb

Programmers/튜플/튜플_김수빈.java
#46 튜플
너무 정석대로 푸니까 논리구조 짜는게 힘들었다.
-
=> solved 튜플 - 110.13ms, 118mb

Programmers/압축/압축_김수빈.java
=> solved 압축 - 0.81ms, 94.1mb

Baekjoon/풍선/풍선_김수빈.java
=> solved 풍선 - 288ms, 24116kb

Programmers/방금그곡/방금그곡_허승경.java
#80 
보통이었습니다.
- replaceAll()
- 시간은 모두 분으로 바꾸기
=> solved 방금그곡 - 15.09ms 94.7mb

Programmers/괄호변환/괄호변환_허승경.java
#101 
문제에 나온 그대로 풀면 됐습니다
- 재귀
- stack
- 문자열 분리
=> solved 괄호변환 - 2.28ms 92.6mb

Baekjoon/크리스마스트리/크리스마스트리_김수빈.java
#102 
어려웠다. dp랑 순열과 조합이 마구잡이로 섞여서 날 곤란하게 했다.
- dp
- 순열
=> unsolved 크리스마스 트리 - 184ms, 119724kb

Baekjoon/물대기/물대기_박단비.py
=> solved 물대기 - 172ms 40936kb

Programmers/택배상자/택배상자_박단비.py
=> solved 택배상자 - 280.08ms 78.5mb

Programmers/방금그곡/방금그곡_박단비.py
=> solved 방금그곡 - 1.71ms 9.5mb

Baekjoon/핑크플로이드/핑크플로이드_박단비.py
=> solved 핑크플로이드 - 960ms 104600kb

Programmers/우박수열정적분/우박수열정적분_허승경.java
#103 
요란한(?) 문제 설명에 비해 풀이는 어렵지 않은 것 같습니다.
문제의 요구 사항을 파악하는 게 정말 중요한 것 같습니다..!
- 사다리꼴 넓이 공식
=> solved 우박수열정적분 - 23.33ms 102mb

Baekjoon/퍼거슨과사과/퍼거슨과사과_허승경.java
#119 
쉬웠습니다.
이 문제는 시간단축이 포인트 같습니다~
- 최대공약수와 약수
=> solved 퍼거슨과사과 - 128ms 16.340mb

Programmers/괄호변환/괄호변환_박단비.py
=> solved 괄호변환 - 12.60ms 9.31mb

Baekjoon/크리스마스트리/크리스마스트리_박단비.py
=> solved 크리스마스트리 - 2904ms 78568kb

Baekjoon/퍼거슨과사과/퍼거슨과사과_김수빈.java
=> solved 퍼거슨과 사과 - 1728ms, 16684kb
